/**
 * Sandbox container exercising the adobe-consent extension end to end.
 *
 * Generated by `reactor-sandbox init`, then filled in so the emitted Turbine
 * library actually includes the main module, the vendored CMP bundle, an event,
 * a condition, an action, and the data elements.
 */
module.exports = {
  rules: [
    {
      name: 'Consent changed -> re-scan blocked tags',
      events: [
        {
          modulePath: 'adobe-consent/src/lib/events/consentChanged.js',
          settings: { includeInitial: true }
        }
      ],
      conditions: [
        {
          modulePath: 'adobe-consent/src/lib/conditions/hasConsent.js',
          settings: { category: 'analytics' }
        }
      ],
      actions: [
        {
          modulePath: 'adobe-consent/src/lib/actions/rescanTags.js',
          settings: {}
        }
      ]
    },
    {
      name: 'Analytics granted -> set consent',
      events: [
        {
          modulePath: 'adobe-consent/src/lib/events/consentGranted.js',
          settings: { category: 'analytics' }
        }
      ],
      conditions: [],
      actions: [
        {
          modulePath: 'adobe-consent/src/lib/actions/setConsent.js',
          settings: { mode: 'update', grant: 'analytics' }
        }
      ]
    }
  ],
  dataElements: {
    consentStatus: {
      modulePath: 'adobe-consent/src/lib/dataElements/consentStatus.js',
      settings: { category: 'analytics', format: 'yn' }
    },
    consentSummary: {
      modulePath: 'adobe-consent/src/lib/dataElements/consentSummary.js',
      settings: {}
    },
    consentRegion: {
      modulePath: 'adobe-consent/src/lib/dataElements/consentRegion.js',
      settings: {}
    },
    consentXdm: {
      modulePath: 'adobe-consent/src/lib/dataElements/consentXdm.js',
      settings: {}
    }
  },
  extensions: {
    'adobe-consent': {
      displayName: 'Adobe Consent — Cookie Consent Manager',
      settings: {
        policyVersion: 1,
        model: 'opt_in',
        region: 'DE',
        honorGpc: true,
        autoBlock: true,
        debug: true,
        webSdkEnabled: true,
        webSdkStandardVersion: '2.0',
        optInEnabled: true,
        analyticsEnabled: true,
        dataLayerEnabled: true,
        launchDirectCallEnabled: true,
        title: 'Your privacy, your altitude'
      }
    }
  },
  company: {
    id: 'CO12345',
    orgId: 'ABCDEFGHIJKLMNOPQRSTUVWX@AdobeOrg',
    tenantId: 'fake-tenant-id'
  },
  property: {
    name: 'Sandbox property',
    settings: {
      id: 'PR12345',
      domains: ['adobe.com', 'example.com'],
      undefinedVarsReturnEmpty: false
    }
  },
  buildInfo: {
    turbineVersion: '27.2.0',
    turbineBuildDate: '2021-08-11T20:25:49Z',
    buildDate: '2022-01-01T12:10:33Z',
    environment: 'development' // deprecated, use environment block instead
  },
  environment: {
    id: 'EN00000000000000000000000000000000',
    stage: 'development'
  }
};
